///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
sealed class Assets {
  Assets._();

  static const String imagesCoffeeCup1 = 'assets/images/coffee_cup_1.webp';
  static const String imagesCoffeeCup2 = 'assets/images/coffee_cup_2.webp';
  static const String imagesCoffeeCup3 = 'assets/images/coffee_cup_3.webp';
  static const String imagesPlaceholder = 'assets/images/placeholder.webp';
}
