name: flutter_coffee_shop
description: "Laboratory work on the Effective course."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  go_router: ^13.2.0
  gap: ^3.0.1
  analyzer: ^6.2.0
  flutter_svg: ^2.0.10+1
  flutter_dotenv: ^5.1.0
  uuid: ^4.3.3
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  build_verify: ^3.1.0
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9
  custom_lint: ^0.6.2
  go_router_builder: ^2.4.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

flutter_assets_generator:
  output_dir: src\common\assets